module.exports = {
  preset: 'ts-jest',
  testEnvironment: 'node',
  forceExit: true,
  coveragePathIgnorePatterns: [
    'src/app.ts',
    'src/https.ts',
    'src/paths.ts',
    'src/services/ethereum-base.ts',
    'src/services/telemetry-transport.ts',
    'src/chains/avalanche/avalanche.ts',
    'src/chains/ethereum/ethereum.ts',
    'src/chains/solana/solana.ts',
    'src/connectors/uniswap/uniswap.ts',
    'src/connectors/uniswap/uniswap.v3.ts',
    'src/connectors/uniswap/uniswap.v3.helper.ts',
    'src/connectors/uniswap/uniswap.config.ts',
    'src/connectors/pangolin/pangolin.ts',
    'src/connectors/pangolin/pangolin.config.ts',
    'conf/migration/migrations.js',
  ],
  modulePathIgnorePatterns: ['<rootDir>/dist/'],
  setupFilesAfterEnv: ['<rootDir>/test/setupTests.js'],
};
